# APT 업데이트 및 전체 패키지 업그레이드
- name: Update apt cache and upgrade all packages
  apt:
    update_cache: yes
    upgrade: dist

# 공통 패키지 설치
- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: yes

#  NTP 패키지 제거
- name: Remove NTP
  apt:
    name: ntp
    state: absent
    purge: yes