- name: Create symbolic link for noHands.jmx
  become: true
  file:
    src: /opt/jmeter/test_plan.jmx
    dest: /opt/jmeter/noHands.jmx
    state: link
    force: true


- name: Copy run.sh script
  copy:
    src: run.sh
    dest: /opt/jmeter/run.sh
    mode: '0755'
