- name: DEBUG - 수정
  debug:
    msg: "진짜 수정함"

- name: Download CloudWatch Agent installer
  become: yes
  get_url:
    url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
    dest: /tmp/amazon-cloudwatch-agent.deb
    mode: '0644'

- name: Install CloudWatch Agent
  become: true
  command: dpkg -i /tmp/amazon-cloudwatch-agent.deb