- name: Update apt cache and upgrade all packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: yes

- name: Remove NTP
  apt:
    name: ntp
    state: absent
    purge: yes

- name: Set timezone to Asia/Seoul
  timezone:
    name: Asia/Seoul